In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"E:\Programming\NLP\bag_of_words\spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
def ge_spam_number(x):
    if x == 'spam':
        return 1
    else:
        return 0

In [9]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =="spam" else 0)

In [10]:
df.shape


(5572, 3)

In [11]:
df.head()


Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:4]

4181    swhrt how u dey,hope ur ok, tot about u 2day.l...
394     Yes i think so. I am in office but my lap is i...
2193    Congrats ! Treat pending.i am not on mail for ...
1188    There's no point hangin on to mr not right if ...
Name: Message, dtype: object

In [16]:
type(X_train.values)

numpy.ndarray

In [33]:
type(y_train)

pandas.core.series.Series

In [34]:
y_train[:4
]

4181    0
394     0
2193    0
1188    0
Name: spam, dtype: int64

Create bag of words representation using CountVectorizer


In [19]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7791 sparse matrix of type '<class 'numpy.int64'>'
	with 59718 stored elements in Compressed Sparse Row format>

In [35]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
X_train_cv.shape

(4457, 7791)

In [37]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zoom', 'zyada', 'èn'], dtype=object)

In [38]:
v.get_feature_names_out()[100:150]

array(['08712402050', '08712402578', '08712402902', '08712402972',
       '08712404000', '08712405020', '08712405022', '08712460324',
       '08712466669', '0871277810710p', '0871277810810', '0871277810910p',
       '08714342399', '087147123779am', '08714712379', '08714712394',
       '08714712412', '08715203028', '08715203649', '08715203656',
       '08715203677', '08715203685', '08715203694', '08715205273',
       '08715500022', '08715705022', '08717111821', '08717168528',
       '08717205546', '0871750', '08717507382', '08717509990',
       '08717890890', '08717895698', '08717898035', '08718711108',
       '08718720201', '08718723815', '08718726270', '087187262701',
       '08718726970', '08718726971', '08718726978', '087187272008',
       '08718727870', '08718727870150ppm', '08718730555', '08718730666',
       '08718738001', '08718738002'], dtype=object)

In [39]:
v.get_feature_names_out()[1771]

'checking'

In [40]:
v.vocabulary_

{'swhrt': 6700,
 'how': 3563,
 'dey': 2305,
 'hope': 3531,
 'ur': 7249,
 'ok': 4956,
 'tot': 7040,
 'about': 763,
 '2day': 382,
 'love': 4263,
 'miss': 4543,
 'take': 6732,
 'care': 1670,
 'yes': 7738,
 'think': 6887,
 'so': 6319,
 'am': 939,
 'in': 3684,
 'office': 4940,
 'but': 1593,
 'my': 4704,
 'lap': 4052,
 'is': 3786,
 'room': 5861,
 'thats': 6856,
 'on': 4973,
 'for': 2967,
 'the': 6857,
 'last': 4061,
 'few': 2842,
 'days': 2208,
 'didnt': 2324,
 'shut': 6181,
 'that': 6853,
 'down': 2448,
 'congrats': 1982,
 'treat': 7079,
 'pending': 5184,
 'not': 4863,
 'mail': 4352,
 'will': 7567,
 'once': 4977,
 'thru': 6922,
 'respect': 5781,
 'mother': 4628,
 'at': 1124,
 'home': 3516,
 'check': 1768,
 'mails': 4355,
 'there': 6874,
 'no': 4833,
 'point': 5327,
 'hangin': 3355,
 'to': 6980,
 'mr': 4647,
 'right': 5825,
 'if': 3645,
 'he': 3405,
 'makin': 4363,
 'happy': 3371,
 'urgent': 7252,
 'this': 6895,
 'our': 5046,
 '2nd': 404,
 'attempt': 1136,
 'contact': 1998,
 'your': 7761,
 '

In [41]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
np.where(X_train_np[0]!=0)

(array([ 382,  763, 1670, 2305, 3531, 3563, 4263, 4543, 4956, 6700, 6732,
        7040, 7249], dtype=int64),)

In [43]:
X_train[:4]


4181    swhrt how u dey,hope ur ok, tot about u 2day.l...
394     Yes i think so. I am in office but my lap is i...
2193    Congrats ! Treat pending.i am not on mail for ...
1188    There's no point hangin on to mr not right if ...
Name: Message, dtype: object

In [46]:
X_train_np[0][1771]

0

Train the naive bayes model


In [47]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [48]:
X_test_cv = v.transform(X_test)


Evaluate Performance


In [49]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       967
           1       0.96      0.92      0.94       148

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [50]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

Train the model using sklearn pipeline and reduce number of lines of code

In [52]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [53]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [54]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       967
           1       0.96      0.92      0.94       148

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [56]:
clf.predict(emails)

array([0, 1], dtype=int64)